import {Configuration, OpenAIApi} from 'openai'

const OPENAI_API_KEY = process.env.OPENAI_API_KEY
const OPEN_AI_MODEL = 'gpt-3.5-turbo'

const configuration = new Configuration({
    apiKey: OPENAI_API_KEY,
})
const openai = new OpenAIApi(configuration)

/**
 * getCompletion uses the OpenAI API to generate a response to a prompt
 * @param prompt the prompt to generate a response to
 * @param systemPromptText the system prompt to use, if not provided, a default system prompt will be used
 * @returns the response generated by the OpenAI API
 * @throws an error if the OpenAI API key is not configured
 * @throws an error if the OpenAI API request fails
 **/
export const getCompletion = async function (prompt, systemPromptText = '') {
    if (!OPENAI_API_KEY) {
        console.error('OpenAI API key not configured, please follow instructions in README.md')
        return
    }
    try {
        // format the date as Mon-dd-yyyy
        const date = new Date()
        const month = date.toLocaleString('default', {month: 'short'})
        const day = date.getDate()
        const year = date.getFullYear()
        const formatted_date = `${month}-${day}-${year}`

        // add a system prompt to the prompt
        let systemPrompt = {
            role: 'system',
            content: `You are MyBot, a large language model trained by OpenAI. Answer as concisely as possible. Your responses are neatly organized, always taking advantage of Markdown syntax, lists, formatting, and images to improve readability and cohesion. Always use new lines in between your paragraphs to make it easier to read. When asked to do tasks, you first think step by step, and break the problem down into parts to reach the most accurate answer documenting along the way. Knowledge cutoff Current date: ${formatted_date}`,
        }

        // allow the system prompt to be overridden
        if (systemPromptText) {
            systemPrompt = {role: 'system', content: systemPromptText}
        }

        // combine the system prompt with the user prompt in an array
        const combinedPrompt = [systemPrompt, ...prompt]
        console.log('combinedPrompt', combinedPrompt)
        // format the prompt
        const completion = await openai.createChatCompletion({
            model: OPEN_AI_MODEL,
            messages: combinedPrompt,
            // the temperature parameter controls the randomness of the response
            // the higher the temperature, the more random the response
            // the lower the temperature, the more likely the response will be a continuation of the prompt
            temperature: 0.7,
        })

        let reply = completion?.data?.choices[0]?.message?.content.trim()

        return reply
    } catch (error: any) {
        if (error.response) {
            console.error(
                'Error with OpenAI API request',
                error.response.status,
                error.response.data
            )
        } else {
            console.error(`Error with OpenAI API request: ${error.message}`)
        }
        return error
    }
}

export const getEmbedding = async text => {
    if (!text) return
    if (!OPENAI_API_KEY) {
        console.error('OpenAI API key not configured, please follow instructions in README.md')
        return
    }
    try {
        // each input must not exceed 8192 tokens in length.
        const response = await openai.createEmbedding({
            model: 'text-embedding-ada-002',
            input: text,
        })

        const responseData = response.data.data[0].embedding

        return responseData
    } catch (error) {
        return error
    }
}

export const getAiImage = async prompt => {
    const response = await openai.createImage({
        prompt: prompt,
        n: 1,
        size: '512x512',
    })
    const responseImageUrl = response['data']['data'][0]['url']
    return responseImageUrl
}
